"use strict";
// Conditional Tests
let car = "subaru";
console.log("Is car == 'subaru'? I predict True.");
console.log(car == "subaru");
console.log("Is car == 'honda'? I predict False.");
console.log(car == "honda");
console.log("Is car != 'toyota'? I predict True.");
console.log(car != "toyota");
console.log("Is car != 'subaru'? I predict False.");
console.log(car != "subaru");
console.log("Is car === 'Subaru'? I predict False.");
console.log(car === "Subaru");
console.log("Is car !== 'Subaru'? I predict True.");
console.log(car !== "Subaru");
console.log("Is car.length == 6? I predict True.");
console.log(car.length == 6);
console.log("Is car.length == 7? I predict False.");
console.log(car.length == 7);
console.log("Is car.toUpperCase() == 'SUBARU'? I predict True.");
console.log(car.toUpperCase() == "SUBARU");
console.log("Is car.toUpperCase() == 'HONDA'? I predict False.");
console.log(car.toUpperCase() == "HONDA");
